name: Bug Report
description: Report a bug or unexpected behaviour in bptools
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: bptools version
      placeholder: "e.g. v2026.02.13.1"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Linux (amd64)
        - Linux (arm64)
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows (amd64)
        - Docker
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `bptools -services ...`
        2. ...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: AWS region, relevant environment variables, error output, etc.
