package fixes

import (
	"bptools/awsdata"
	"bptools/fix"
	"bptools/fix/pool"

	cloudtrailtypes "github.com/aws/aws-sdk-go-v2/service/cloudtrail/types"
	inspector2types "github.com/aws/aws-sdk-go-v2/service/inspector2/types"
)

// RegisterAllFixes registers every available FixAction with the fix registry.
// Call this after RegisterAllChecks, immediately before RunFixes.
func RegisterAllFixes(d *awsdata.Data) {
	p := pool.NewS3BucketPool(d.Clients.S3, d.Clients.ResourceGroupsTagging)

	// NO_IMPACT / LOW
	fix.Register(&rdsInstanceAutoMinorVersionFix{clients: d.Clients})
	fix.Register(&rdsClusterAutoMinorVersionFix{clients: d.Clients})
	fix.Register(&ec2DetailedMonitoringFix{clients: d.Clients})
	fix.Register(&lambdaXRayFix{clients: d.Clients})
	fix.Register(&elastiCacheAutoMinorVersionFix{clients: d.Clients})
	fix.Register(&redshiftVersionUpgradeFix{clients: d.Clients})
	fix.Register(&kmsKeyRotationFix{clients: d.Clients})
	fix.Register(&neptuneCopyTagsToSnapshotFix{clients: d.Clients})
	fix.Register(&kinesisRetentionFix{clients: d.Clients})
	fix.Register(&dmsAutoMinorVersionFix{clients: d.Clients})
	fix.Register(&mqAutoMinorVersionFix{checkID: "mq-automatic-minor-version-upgrade-enabled", clients: d.Clients})
	fix.Register(&mqAutoMinorVersionFix{checkID: "mq-auto-minor-version-upgrade-enabled", clients: d.Clients})
	fix.Register(newAthenaEngineAutoUpgradeFix(d.Clients))
	fix.Register(&rdsCopyTagsToSnapshotClusterFix{checkID: "rds-mysql-cluster-copy-tags-to-snapshot-check", clients: d.Clients})
	fix.Register(&rdsCopyTagsToSnapshotClusterFix{checkID: "rds-pgsql-cluster-copy-tags-to-snapshot-check", clients: d.Clients})
	fix.Register(&appConfigApplicationDescriptionFix{clients: d.Clients})
	fix.Register(&appConfigEnvironmentDescriptionFix{clients: d.Clients})
	fix.Register(&appConfigDeploymentStrategyDescriptionFix{clients: d.Clients})
	fix.Register(&appConfigMinimumFinalBakeTimeFix{clients: d.Clients})
	fix.Register(&appConfigTagFix{checkID: "appconfig-application-tagged", kind: "application", clients: d.Clients})
	fix.Register(&appConfigTagFix{checkID: "appconfig-environment-tagged", kind: "environment", clients: d.Clients})
	fix.Register(&appConfigTagFix{checkID: "appconfig-configuration-profile-tagged", kind: "configurationprofile", clients: d.Clients})
	fix.Register(&appConfigTagFix{checkID: "appconfig-deployment-strategy-tagged", kind: "deploymentstrategy", clients: d.Clients})
	fix.Register(&appConfigTagFix{checkID: "appconfig-extension-association-tagged", kind: "extensionassociation", clients: d.Clients})
	fix.Register(&amplifyAppDescriptionFix{clients: d.Clients})
	fix.Register(&amplifyBranchAutoDeletionFix{clients: d.Clients})
	fix.Register(&amplifyAppTagFix{clients: d.Clients})
	fix.Register(&amplifyAppNoEnvVarsFix{clients: d.Clients})
	fix.Register(&amplifyBranchDescriptionFix{clients: d.Clients})
	fix.Register(&amplifyBranchPerformanceModeFix{clients: d.Clients})
	fix.Register(&amplifyBranchTagFix{clients: d.Clients})
	fix.Register(&ecrRepositoryTaggedFix{clients: d.Clients})
	fix.Register(&iamOIDCProviderTaggedFix{clients: d.Clients})
	fix.Register(&iamSAMLProviderTaggedFix{clients: d.Clients})
	fix.Register(&iamServerCertificateTaggedFix{clients: d.Clients})
	fix.Register(&lambdaFunctionDescriptionFix{clients: d.Clients})
	fix.Register(&lambdaConcurrencyFix{clients: d.Clients})
	fix.Register(&lambdaPublicAccessFix{clients: d.Clients})
	fix.Register(&lambdaDLQFix{clients: d.Clients})
	fix.Register(&appIntegrationsEventDescriptionFix{clients: d.Clients})
	fix.Register(&iotProvisioningTemplateDescriptionFix{clients: d.Clients})
	fix.Register(&iotProvisioningTemplateJITPFix{clients: d.Clients})
	fix.Register(&iotAuthorizerTokenSigningFix{clients: d.Clients})
	fix.Register(&athenaDataCatalogDescriptionFix{clients: d.Clients})
	fix.Register(&athenaPreparedStatementDescriptionFix{clients: d.Clients})
	fix.Register(&athenaWorkgroupDescriptionFix{clients: d.Clients})
	fix.Register(&ebApplicationDescriptionFix{clients: d.Clients})
	fix.Register(&ebApplicationVersionDescriptionFix{clients: d.Clients})
	fix.Register(&ebEnvironmentDescriptionFix{clients: d.Clients})
	fix.Register(&transferAgreementDescriptionFix{clients: d.Clients})
	fix.Register(&transferCertificateDescriptionFix{clients: d.Clients})
	fix.Register(&sagemakerImageDescriptionFix{clients: d.Clients})
	fix.Register(&sagemakerDomainInVPCFix{clients: d.Clients})
	fix.Register(&lightsailBucketPublicOverridesFix{clients: d.Clients})
	fix.Register(&ec2TrafficMirrorSessionDescriptionFix{clients: d.Clients})
	fix.Register(&evidentlyProjectDescriptionFix{clients: d.Clients})
	fix.Register(&evidentlyLaunchDescriptionFix{clients: d.Clients})
	fix.Register(&transferConnectorLoggingFix{clients: d.Clients})

	// NO_IMPACT / MEDIUM
	fix.Register(newELBLoggingFix(d.Clients, p))
	fix.Register(newCloudFrontAccessLogsFix(d.Clients, p))
	fix.Register(&elbCrossZoneFix{clients: d.Clients})
	fix.Register(newS3LoggingFix(d.Clients, p))
	fix.Register(&s3VersioningFix{clients: d.Clients})
	fix.Register(&dynamoDBPITRFix{clients: d.Clients})
	fix.Register(&rdsInstanceIAMAuthFix{clients: d.Clients})
	fix.Register(&rdsClusterIAMAuthFix{clients: d.Clients})
	fix.Register(&rdsInstanceLoggingFix{clients: d.Clients})
	fix.Register(&rdsInstanceBackupFix{clients: d.Clients})
	fix.Register(&neptuneIAMAuthFix{clients: d.Clients})
	fix.Register(&efsBackupFix{clients: d.Clients})
	fix.Register(&sesTLSRequiredFix{clients: d.Clients})
	fix.Register(newAthenaEnforceWorkgroupConfigFix(d.Clients))
	fix.Register(newAthenaCloudWatchMetricsFix(d.Clients))
	fix.Register(&cwLogGroupRetentionFix{clients: d.Clients})
	fix.Register(&ebLogsToCloudWatchFix{clients: d.Clients})
	fix.Register(&glueJobLoggingFix{clients: d.Clients})
	fix.Register(&cognitoAdvancedSecurityFix{clients: d.Clients})
	fix.Register(&cognitoPasswordPolicyFix{clients: d.Clients})
	fix.Register(&cognitoMFAFix{clients: d.Clients})
	fix.Register(&codeBuildS3LogsEncryptionFix{clients: d.Clients})
	fix.Register(&codeBuildProjectLoggingFix{clients: d.Clients})
	fix.Register(&appConfigValidatorsFix{clients: d.Clients})
	fix.Register(&rdsAuroraMySQLClusterLoggingFix{checkID: "rds-aurora-mysql-audit-logging-enabled", clients: d.Clients})
	fix.Register(&rdsAuroraMySQLClusterLoggingFix{checkID: "aurora-mysql-cluster-audit-logging", clients: d.Clients})
	fix.Register(&rdsAuroraPostgreSQLLoggingFix{clients: d.Clients})
	fix.Register(&docDBClusterAuditLoggingFix{clients: d.Clients})
	fix.Register(&docDBClusterBackupRetentionFix{clients: d.Clients})
	fix.Register(&cloudTrailLogFileValidationFix{clients: d.Clients})
	fix.Register(&ecsContainerInsightsFix{clients: d.Clients})
	fix.Register(&ecsContainersNonprivilegedFix{clients: d.Clients})
	fix.Register(&ecsContainersReadOnlyFix{clients: d.Clients})
	fix.Register(&eksLoggingFix{checkID: "eks-cluster-logging-enabled", clients: d.Clients})
	fix.Register(&eksLoggingFix{checkID: "eks-cluster-log-enabled", clients: d.Clients})
	fix.Register(&nlbCrossZoneFix{clients: d.Clients})
	fix.Register(newNLBLoggingFix(d.Clients, p))
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-s3-protection-enabled", featureName: "S3_DATA_EVENTS", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-eks-protection-audit-enabled", featureName: "EKS_AUDIT_LOGS", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-eks-protection-runtime-enabled", featureName: "EKS_RUNTIME_MONITORING", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-ecs-protection-runtime-enabled", featureName: "ECS_RUNTIME_MONITORING", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-ec2-protection-runtime-enabled", featureName: "EC2_RUNTIME_MONITORING", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-lambda-protection-enabled", featureName: "LAMBDA_NETWORK_LOGS", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-rds-protection-enabled", featureName: "RDS_LOGIN_EVENTS", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-malware-protection-enabled", featureName: "EBS_MALWARE_PROTECTION", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-runtime-monitoring-enabled", featureName: "RUNTIME_MONITORING", clients: d.Clients})

	// NO_IMPACT / HIGH
	fix.Register(&iamPasswordPolicyFix{clients: d.Clients})
	fix.Register(&iamAccessAnalyzerFix{clients: d.Clients})
	fix.Register(&netfwDeletionProtectionFix{clients: d.Clients})
	fix.Register(&netfwSubnetChangeProtectionFix{clients: d.Clients})
	fix.Register(&netfwLoggingFix{clients: d.Clients})
	fix.Register(&cognitoUserPoolDeletionProtectionFix{clients: d.Clients})
	fix.Register(&kmsCancelDeletionFix{clients: d.Clients})
	fix.Register(&docDBDeletionProtectionFix{clients: d.Clients})
	fix.Register(&neptuneDeletionProtectionFix{clients: d.Clients})
	fix.Register(&cloudFormationTerminationProtectionFix{clients: d.Clients})
	fix.Register(&kinesisEncryptionFix{clients: d.Clients})
	fix.Register(&kmsKeyTaggedFix{clients: d.Clients})
	fix.Register(&ssmBlockPublicSharingFix{clients: d.Clients})
	fix.Register(&emrBlockPublicAccessFix{clients: d.Clients})
	fix.Register(newElasticsearchEncryptionAtRestFix(d.Clients))
	fix.Register(newElasticsearchNodeToNodeEncryptionFix(d.Clients))
	fix.Register(newAthenaEncryptionAtRestFix(d.Clients))
	fix.Register(&cloudFrontAssociatedWithWAFFix{clients: d.Clients})
	fix.Register(&codeBuildArtifactEncryptionFix{clients: d.Clients})
	fix.Register(&inspector2Fix{checkID: "inspector-ec2-scan-enabled", description: "Enable Inspector2 EC2 scanning", resourceType: inspector2types.ResourceScanTypeEc2, clients: d.Clients})
	fix.Register(&inspector2Fix{checkID: "inspector-ecr-scan-enabled", description: "Enable Inspector2 ECR scanning", resourceType: inspector2types.ResourceScanTypeEcr, clients: d.Clients})
	fix.Register(&inspector2Fix{checkID: "inspector-lambda-standard-scan-enabled", description: "Enable Inspector2 Lambda standard scanning", resourceType: inspector2types.ResourceScanTypeLambda, clients: d.Clients})
	fix.Register(&inspector2Fix{checkID: "inspector-lambda-code-scan-enabled", description: "Enable Inspector2 Lambda code scanning", resourceType: inspector2types.ResourceScanTypeLambdaCode, clients: d.Clients})
	fix.Register(&vpcDefaultSGClosedFix{clients: d.Clients})
	fix.Register(&ebsSnapshotBlockPublicAccessFix{clients: d.Clients})
	fix.Register(&rdsInstanceDeletionProtectionFix{clients: d.Clients})
	fix.Register(&rdsClusterDeletionProtectionFix{clients: d.Clients})
	fix.Register(&dynamoDBDeletionProtectionFix{clients: d.Clients})
	fix.Register(&dynamoDBSSEFix{clients: d.Clients})
	fix.Register(&cloudTrailLoggingFix{clients: d.Clients})
	fix.Register(&s3EncryptionFix{clients: d.Clients})
	fix.Register(&s3PublicAccessBlockFix{checkID: "s3-bucket-level-public-access-prohibited", clients: d.Clients})
	fix.Register(&s3PublicAccessBlockFix{checkID: "s3-bucket-public-read-prohibited", clients: d.Clients})
	fix.Register(&s3PublicAccessBlockFix{checkID: "s3-bucket-public-write-prohibited", clients: d.Clients})
	fix.Register(&s3AccountPublicAccessBlockFix{checkID: "s3-account-level-public-access-blocks", clients: d.Clients})
	fix.Register(&s3AccountPublicAccessBlockFix{checkID: "s3-account-level-public-access-blocks-periodic", clients: d.Clients})
	fix.Register(&ec2EBSEncryptionFix{clients: d.Clients})
	fix.Register(&ec2TransitGatewayAutoAttachFix{clients: d.Clients})
	fix.Register(&guardDutyFix{clients: d.Clients})
	fix.Register(&securityHubFix{clients: d.Clients})
	fix.Register(newOpenSearchEncryptionAtRestFix(d.Clients))
	fix.Register(newOpenSearchNodeToNodeEncryptionFix(d.Clients))
	fix.Register(newOpenSearchHTTPSFix(d.Clients))
	fix.Register(&opensearchAuditLoggingFix{clients: d.Clients})

	// NO_IMPACT / MEDIUM (continued)
	fix.Register(&elastiCacheAutoFailoverFix{clients: d.Clients})
	fix.Register(&elastiCacheBackupFix{clients: d.Clients})
	fix.Register(&elastiCacheRedisBackupFix{clients: d.Clients})
	fix.Register(&redshiftEnhancedVPCRoutingFix{clients: d.Clients})
	fix.Register(&redshiftBackupFix{clients: d.Clients})
	fix.Register(newRedshiftAuditLoggingFix(d.Clients, p))
	fix.Register(&redshiftServerlessLogsFix{clients: d.Clients})
	fix.Register(&redshiftServerlessEnhancedVPCFix{clients: d.Clients})
	fix.Register(&macieFix{clients: d.Clients})
	fix.Register(&neptuneBackupRetentionFix{clients: d.Clients})
	fix.Register(&neptuneCloudWatchLogsFix{clients: d.Clients})
	fix.Register(&mqGeneralLoggingFix{clients: d.Clients})
	fix.Register(&mqAuditLoggingFix{checkID: "mq-cloudwatch-audit-logging-enabled", clients: d.Clients})
	fix.Register(&mqAuditLoggingFix{checkID: "mq-cloudwatch-audit-log-enabled", clients: d.Clients})
	fix.Register(&apigwV1ExecutionLoggingFix{clients: d.Clients})
	fix.Register(&albDropInvalidHeaderFix{clients: d.Clients})
	fix.Register(&elbDeletionProtectionFix{clients: d.Clients})
	fix.Register(&s3SSLOnlyFix{clients: d.Clients})
	fix.Register(&mariadbCloudWatchLogsFix{clients: d.Clients})
	fix.Register(&auroraMySQLBacktrackingFix{clients: d.Clients})
	fix.Register(&subnetAutoAssignPublicIPFix{clients: d.Clients})
	fix.Register(&dmsEndpointSSLFix{clients: d.Clients})
	fix.Register(&dmsReplicationTaskLoggingFix{checkID: "dms-replication-task-sourcedb-logging", source: true, clients: d.Clients})
	fix.Register(&dmsReplicationTaskLoggingFix{checkID: "dms-replication-task-targetdb-logging", source: false, clients: d.Clients})
	fix.Register(&apigwV1SSLFix{clients: d.Clients})
	fix.Register(&firehoseEncryptionFix{clients: d.Clients})
	fix.Register(&cloudTrailS3DataEventsFix{clients: d.Clients})
	fix.Register(&ssmAutomationLoggingFix{clients: d.Clients})
	fix.Register(&connectInstanceLoggingFix{clients: d.Clients})
	fix.Register(&route53QueryLoggingFix{clients: d.Clients})
	fix.Register(&route53TagFix{checkID: "route53-health-check-tagged", resourceType: "healthcheck", clients: d.Clients})
	fix.Register(&route53TagFix{checkID: "route53-hosted-zone-tagged", resourceType: "hostedzone", clients: d.Clients})
	fix.Register(&route53ResolverTagFix{checkID: "route53-resolver-firewall-domain-list-tagged", clients: d.Clients})
	fix.Register(&route53ResolverTagFix{checkID: "route53-resolver-firewall-rule-group-association-tagged", clients: d.Clients})
	fix.Register(&route53ResolverTagFix{checkID: "route53-resolver-firewall-rule-group-tagged", clients: d.Clients})
	fix.Register(&route53ResolverTagFix{checkID: "route53-resolver-resolver-rule-tagged", clients: d.Clients})
	fix.Register(&cloudTrailS3AllDataEventsFix{checkID: "cloudtrail-all-read-s3-data-event-check", readWrite: cloudtrailtypes.ReadWriteTypeReadOnly, clients: d.Clients})
	fix.Register(&cloudTrailS3AllDataEventsFix{checkID: "cloudtrail-all-write-s3-data-event-check", readWrite: cloudtrailtypes.ReadWriteTypeWriteOnly, clients: d.Clients})
	fix.Register(&rdsPostgreSQLLoggingFix{clients: d.Clients})
	fix.Register(&rdsSQLServerLoggingFix{clients: d.Clients})
	fix.Register(&rdsProxyTLSFix{clients: d.Clients})
	fix.Register(&ecrImageScanningFix{clients: d.Clients})
	fix.Register(&ecrTagImmutabilityFix{clients: d.Clients})
	fix.Register(&ecrLifecyclePolicyFix{clients: d.Clients})
	fix.Register(&ec2ENISourceDestCheckFix{clients: d.Clients})
	fix.Register(&ec2LaunchTemplateIMDSv2Fix{clients: d.Clients})
	fix.Register(&ec2LaunchTemplatePublicIPFix{clients: d.Clients})
	fix.Register(&ec2ClientVPNLoggingFix{clients: d.Clients})
	fix.Register(&ec2VPNConnectionLoggingFix{clients: d.Clients})
	fix.Register(&sfnLoggingFix{clients: d.Clients})
	fix.Register(&fsxWindowsAuditLogFix{clients: d.Clients})
	fix.Register(&dataSyncTaskLoggingFix{clients: d.Clients})
	fix.Register(&dataSyncObjectStorageHTTPSFix{clients: d.Clients})
	fix.Register(&cwAlarmActionEnabledFix{clients: d.Clients})
	fix.Register(&cloudWatchMetricStreamTaggedFix{clients: d.Clients})
	fix.Register(&stepFunctionsStateMachineTaggedFix{clients: d.Clients})
	fix.Register(&transferTaggedFix{checkID: "transfer-agreement-tagged", clients: d.Clients})
	fix.Register(&transferTaggedFix{checkID: "transfer-certificate-tagged", clients: d.Clients})
	fix.Register(&transferTaggedFix{checkID: "transfer-connector-tagged", clients: d.Clients})
	fix.Register(&transferTaggedFix{checkID: "transfer-profile-tagged", clients: d.Clients})
	fix.Register(&transferTaggedFix{checkID: "transfer-workflow-tagged", clients: d.Clients})
	fix.Register(&workspacesTaggedFix{checkID: "workspaces-connection-alias-tagged", clients: d.Clients})
	fix.Register(&workspacesTaggedFix{checkID: "workspaces-workspace-tagged", clients: d.Clients})

	// NO_IMPACT / LOW (continued)
	fix.Register(&fsxOpenZFSCopyTagsFix{clients: d.Clients})
	fix.Register(&dataSyncTaskVerificationFix{clients: d.Clients})

	// NO_IMPACT / LOW (continued)
	fix.Register(&codeDeployAutoRollbackFix{clients: d.Clients})
	fix.Register(&codeDeployOutdatedInstancesFix{clients: d.Clients})
	fix.Register(&apigwV2MetricsFix{clients: d.Clients})
	fix.Register(&apigwV2AuthorizationTypeFix{clients: d.Clients})
	fix.Register(&apigwV1EndpointTypeFix{clients: d.Clients})
	fix.Register(&apigwV1RestAPITagFix{clients: d.Clients})
	fix.Register(&apigwV1StageTagFix{clients: d.Clients})
	fix.Register(&ebManagedUpdatesFix{clients: d.Clients})
	fix.Register(&ebEnhancedHealthFix{clients: d.Clients})
	fix.Register(&mskEnhancedMonitoringFix{clients: d.Clients})
	fix.Register(&ec2HopLimitFix{clients: d.Clients})
	fix.Register(&autoscalingCapacityRebalancingFix{clients: d.Clients})
	fix.Register(&autoscalingELBHealthCheckFix{clients: d.Clients})
	fix.Register(&apigwV1XRayFix{clients: d.Clients})
	fix.Register(&appsyncXRayFix{clients: d.Clients})
	fix.Register(&apigwV1StageDescriptionFix{clients: d.Clients})
	fix.Register(&apigwV2StageDescriptionFix{clients: d.Clients})

	// NO_IMPACT / MEDIUM (continued again)
	fix.Register(&sagemakerNotebookRootAccessFix{clients: d.Clients})
	fix.Register(&apigwV1AccessLogsFix{clients: d.Clients})
	fix.Register(&apigwV2AccessLogsFix{clients: d.Clients})
	fix.Register(&apigwV1CacheEncryptedFix{clients: d.Clients})
	fix.Register(&cloudFrontHTTPSFix{clients: d.Clients})
	fix.Register(&cloudFrontDefaultRootObjectFix{clients: d.Clients})
	fix.Register(&cloudFrontNoDeprecatedSSLProtocolsFix{clients: d.Clients})
	fix.Register(&cloudFrontViewerTLSPolicyFix{checkID: "cloudfront-security-policy-check", clients: d.Clients})
	fix.Register(&cloudFrontViewerTLSPolicyFix{checkID: "cloudfront-ssl-policy-check", clients: d.Clients})
	fix.Register(&cloudFrontSniEnabledFix{clients: d.Clients})
	fix.Register(&cloudFrontTrafficToOriginEncryptedFix{clients: d.Clients})
	fix.Register(&cloudFrontS3OriginOACFix{clients: d.Clients})
	fix.Register(&cloudFrontLambdaURLOACFix{clients: d.Clients})
	fix.Register(&cloudFrontOriginAccessIdentityFix{clients: d.Clients})
	fix.Register(&globalEndpointReplicationFix{clients: d.Clients})
	fix.Register(&rumCWLoggingFix{clients: d.Clients})
	fix.Register(&kinesisVideoRetentionFix{clients: d.Clients})
	fix.Register(&appRunnerObservabilityFix{clients: d.Clients})
	fix.Register(&s3KMSEncryptionFix{clients: d.Clients})
	fix.Register(&albDesyncModeFix{clients: d.Clients})
	fix.Register(&clbDesyncModeFix{clients: d.Clients})
	fix.Register(&codeBuildReportGroupEncryptionFix{clients: d.Clients})
	fix.Register(&cloudTrailS3PublicAccessFix{clients: d.Clients})

	// NO_IMPACT / HIGH (continued)
	fix.Register(&ebsSnapshotPublicFix{clients: d.Clients})
	fix.Register(&ec2LaunchTemplateEBSEncryptionFix{clients: d.Clients})
	fix.Register(&docDBSnapshotPublicFix{clients: d.Clients})
	fix.Register(&docDBTLSFix{clients: d.Clients})
	fix.Register(&dynamoDBKMSEncryptionFix{clients: d.Clients})
	fix.Register(&ecsFargatePlatformVersionFix{clients: d.Clients})
	fix.Register(&neptuneSnapshotPublicFix{clients: d.Clients})
	fix.Register(&rdsSnapshotPublicFix{clients: d.Clients})
	fix.Register(&snsKMSEncryptionFix{clients: d.Clients})
	fix.Register(&ssmDocumentNotPublicFix{clients: d.Clients})

	// DEGRADATION / MEDIUM (continued)
	fix.Register(&transferNoFTPFix{clients: d.Clients})

	// DEGRADATION / LOW
	fix.Register(&albHTTPSRedirectFix{clients: d.Clients})

	// DEGRADATION / HIGH
	fix.Register(&sqsNoPublicAccessFix{clients: d.Clients})
	fix.Register(&sqsNoFullAccessFix{clients: d.Clients})
	fix.Register(&snsNoPublicAccessFix{clients: d.Clients})
	fix.Register(&rdsInstancePublicAccessFix{clients: d.Clients})
	fix.Register(&mskPublicAccessFix{clients: d.Clients})
	fix.Register(&redshiftPublicAccessFix{clients: d.Clients})
	fix.Register(&redshiftServerlessPublicAccessFix{clients: d.Clients})

	// DEGRADATION / MEDIUM (instance-level, won't run without explicit --impact-filter)
	fix.Register(&ec2IMDSv2Fix{clients: d.Clients})

	// DEGRADATION / MEDIUM
	fix.Register(&s3ACLProhibitedFix{clients: d.Clients})
	fix.Register(newALBWAFFix(d.Clients))
	fix.Register(&apigwV1WAFAssociationFix{clients: d.Clients})
	fix.Register(&eksEndpointNoPublicAccessFix{clients: d.Clients})

	// DOWN / HIGH
	fix.Register(&rdsMultiAZFix{clients: d.Clients})

	// Multi-agent batch: 50 additional concrete fixers
	registerMultiBatch01(d)
	registerMultiBatch02(d)
	registerMultiBatch03(d)
	registerMultiBatch04(d)
	registerMultiBatch05(d)
	registerMultiBatch06(d)
	registerMultiBatch07(d)
	registerMultiBatch08(d)
	registerMultiBatch09(d)
	registerMultiBatch10(d)
	registerMultiBatch11(d)
	registerMultiBatch12(d)
	registerMultiBatch13(d)
	registerMultiBatch14(d)
	registerMultiBatch15(d)
	registerMultiBatch16(d)
	registerMultiBatch17(d)
	registerMultiBatch18(d)
	registerMultiBatch19(d)
	registerMultiBatch20(d)
	registerMultiBatch21(d)
	registerMultiBatch22(d)
	registerMultiBatch23(d)
	registerMultiBatch24(d)
	registerMultiBatch25(d)
	registerMultiBatch26(d)

	// Ensure every registered check has a corresponding fix action.
	// Concrete fixers above take precedence; uncovered checks get a manual fallback.
	registerGenericTaggedFixes(d)
	registerFallbackFixesForUncoveredRules()
}
