package fixes

import (
	"bptools/awsdata"
	"bptools/fix"
	"bptools/fix/pool"

	cloudtrailtypes "github.com/aws/aws-sdk-go-v2/service/cloudtrail/types"
	inspector2types "github.com/aws/aws-sdk-go-v2/service/inspector2/types"
)

// RegisterAllFixes registers every available FixAction with the fix registry.
// Call this after RegisterAllChecks, immediately before RunFixes.
func RegisterAllFixes(d *awsdata.Data) {
	p := pool.NewS3BucketPool(d.Clients.S3, d.Clients.ResourceGroupsTagging)

	// NO_IMPACT / LOW
	fix.Register(&rdsInstanceAutoMinorVersionFix{clients: d.Clients})
	fix.Register(&rdsClusterAutoMinorVersionFix{clients: d.Clients})
	fix.Register(&ec2DetailedMonitoringFix{clients: d.Clients})
	fix.Register(&lambdaXRayFix{clients: d.Clients})
	fix.Register(&elastiCacheAutoMinorVersionFix{clients: d.Clients})
	fix.Register(&redshiftVersionUpgradeFix{clients: d.Clients})
	fix.Register(&kmsKeyRotationFix{clients: d.Clients})
	fix.Register(&neptuneCopyTagsToSnapshotFix{clients: d.Clients})
	fix.Register(&kinesisRetentionFix{clients: d.Clients})
	fix.Register(&dmsAutoMinorVersionFix{clients: d.Clients})
	fix.Register(&mqAutoMinorVersionFix{checkID: "mq-automatic-minor-version-upgrade-enabled", clients: d.Clients})
	fix.Register(&mqAutoMinorVersionFix{checkID: "mq-auto-minor-version-upgrade-enabled", clients: d.Clients})
	fix.Register(newAthenaEngineAutoUpgradeFix(d.Clients))
	fix.Register(&rdsCopyTagsToSnapshotClusterFix{checkID: "rds-mysql-cluster-copy-tags-to-snapshot-check", clients: d.Clients})
	fix.Register(&rdsCopyTagsToSnapshotClusterFix{checkID: "rds-pgsql-cluster-copy-tags-to-snapshot-check", clients: d.Clients})

	// NO_IMPACT / MEDIUM
	fix.Register(newELBLoggingFix(d.Clients, p))
	fix.Register(&elbCrossZoneFix{clients: d.Clients})
	fix.Register(newS3LoggingFix(d.Clients, p))
	fix.Register(&s3VersioningFix{clients: d.Clients})
	fix.Register(&dynamoDBPITRFix{clients: d.Clients})
	fix.Register(&rdsInstanceIAMAuthFix{clients: d.Clients})
	fix.Register(&rdsClusterIAMAuthFix{clients: d.Clients})
	fix.Register(&rdsInstanceLoggingFix{clients: d.Clients})
	fix.Register(&rdsInstanceBackupFix{clients: d.Clients})
	fix.Register(&neptuneIAMAuthFix{clients: d.Clients})
	fix.Register(&efsBackupFix{clients: d.Clients})
	fix.Register(&sesTLSRequiredFix{clients: d.Clients})
	fix.Register(newAthenaEnforceWorkgroupConfigFix(d.Clients))
	fix.Register(newAthenaCloudWatchMetricsFix(d.Clients))
	fix.Register(&cwLogGroupRetentionFix{clients: d.Clients})
	fix.Register(&ebLogsToCloudWatchFix{clients: d.Clients})
	fix.Register(&glueJobLoggingFix{clients: d.Clients})
	fix.Register(&cognitoAdvancedSecurityFix{clients: d.Clients})
	fix.Register(&cognitoPasswordPolicyFix{clients: d.Clients})
	fix.Register(&cognitoMFAFix{clients: d.Clients})
	fix.Register(&codeBuildS3LogsEncryptionFix{clients: d.Clients})
	fix.Register(&codeBuildProjectLoggingFix{clients: d.Clients})
	fix.Register(&rdsAuroraMySQLClusterLoggingFix{checkID: "rds-aurora-mysql-audit-logging-enabled", clients: d.Clients})
	fix.Register(&rdsAuroraMySQLClusterLoggingFix{checkID: "aurora-mysql-cluster-audit-logging", clients: d.Clients})
	fix.Register(&rdsAuroraPostgreSQLLoggingFix{clients: d.Clients})
	fix.Register(&docDBClusterAuditLoggingFix{clients: d.Clients})
	fix.Register(&docDBClusterBackupRetentionFix{clients: d.Clients})
	fix.Register(&cloudTrailLogFileValidationFix{clients: d.Clients})
	fix.Register(&ecsContainerInsightsFix{clients: d.Clients})
	fix.Register(&ecsContainersNonprivilegedFix{clients: d.Clients})
	fix.Register(&ecsContainersReadOnlyFix{clients: d.Clients})
	fix.Register(&eksLoggingFix{checkID: "eks-cluster-logging-enabled", clients: d.Clients})
	fix.Register(&eksLoggingFix{checkID: "eks-cluster-log-enabled", clients: d.Clients})
	fix.Register(&nlbCrossZoneFix{clients: d.Clients})
	fix.Register(newNLBLoggingFix(d.Clients, p))
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-s3-protection-enabled", featureName: "S3_DATA_EVENTS", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-eks-protection-audit-enabled", featureName: "EKS_AUDIT_LOGS", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-eks-protection-runtime-enabled", featureName: "EKS_RUNTIME_MONITORING", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-ecs-protection-runtime-enabled", featureName: "ECS_RUNTIME_MONITORING", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-ec2-protection-runtime-enabled", featureName: "EC2_RUNTIME_MONITORING", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-lambda-protection-enabled", featureName: "LAMBDA_NETWORK_LOGS", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-rds-protection-enabled", featureName: "RDS_LOGIN_EVENTS", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-malware-protection-enabled", featureName: "EBS_MALWARE_PROTECTION", clients: d.Clients})
	fix.Register(&guardDutyFeatureFix{checkID: "guardduty-runtime-monitoring-enabled", featureName: "RUNTIME_MONITORING", clients: d.Clients})

	// NO_IMPACT / HIGH
	fix.Register(&iamPasswordPolicyFix{clients: d.Clients})
	fix.Register(&iamAccessAnalyzerFix{clients: d.Clients})
	fix.Register(&netfwDeletionProtectionFix{clients: d.Clients})
	fix.Register(&netfwSubnetChangeProtectionFix{clients: d.Clients})
	fix.Register(&netfwLoggingFix{clients: d.Clients})
	fix.Register(&cognitoUserPoolDeletionProtectionFix{clients: d.Clients})
	fix.Register(&kmsCancelDeletionFix{clients: d.Clients})
	fix.Register(&docDBDeletionProtectionFix{clients: d.Clients})
	fix.Register(&neptuneDeletionProtectionFix{clients: d.Clients})
	fix.Register(&cloudFormationTerminationProtectionFix{clients: d.Clients})
	fix.Register(&kinesisEncryptionFix{clients: d.Clients})
	fix.Register(&ssmBlockPublicSharingFix{clients: d.Clients})
	fix.Register(&emrBlockPublicAccessFix{clients: d.Clients})
	fix.Register(newElasticsearchEncryptionAtRestFix(d.Clients))
	fix.Register(newElasticsearchNodeToNodeEncryptionFix(d.Clients))
	fix.Register(newAthenaEncryptionAtRestFix(d.Clients))
	fix.Register(&codeBuildArtifactEncryptionFix{clients: d.Clients})
	fix.Register(&inspector2Fix{checkID: "inspector-ec2-scan-enabled", description: "Enable Inspector2 EC2 scanning", resourceType: inspector2types.ResourceScanTypeEc2, clients: d.Clients})
	fix.Register(&inspector2Fix{checkID: "inspector-ecr-scan-enabled", description: "Enable Inspector2 ECR scanning", resourceType: inspector2types.ResourceScanTypeEcr, clients: d.Clients})
	fix.Register(&inspector2Fix{checkID: "inspector-lambda-standard-scan-enabled", description: "Enable Inspector2 Lambda standard scanning", resourceType: inspector2types.ResourceScanTypeLambda, clients: d.Clients})
	fix.Register(&inspector2Fix{checkID: "inspector-lambda-code-scan-enabled", description: "Enable Inspector2 Lambda code scanning", resourceType: inspector2types.ResourceScanTypeLambdaCode, clients: d.Clients})
	fix.Register(&vpcDefaultSGClosedFix{clients: d.Clients})
	fix.Register(&ebsSnapshotBlockPublicAccessFix{clients: d.Clients})
	fix.Register(&rdsInstanceDeletionProtectionFix{clients: d.Clients})
	fix.Register(&rdsClusterDeletionProtectionFix{clients: d.Clients})
	fix.Register(&dynamoDBDeletionProtectionFix{clients: d.Clients})
	fix.Register(&dynamoDBSSEFix{clients: d.Clients})
	fix.Register(&cloudTrailLoggingFix{clients: d.Clients})
	fix.Register(&s3EncryptionFix{clients: d.Clients})
	fix.Register(&s3PublicAccessBlockFix{checkID: "s3-bucket-level-public-access-prohibited", clients: d.Clients})
	fix.Register(&s3PublicAccessBlockFix{checkID: "s3-bucket-public-read-prohibited", clients: d.Clients})
	fix.Register(&s3PublicAccessBlockFix{checkID: "s3-bucket-public-write-prohibited", clients: d.Clients})
	fix.Register(&s3AccountPublicAccessBlockFix{checkID: "s3-account-level-public-access-blocks", clients: d.Clients})
	fix.Register(&s3AccountPublicAccessBlockFix{checkID: "s3-account-level-public-access-blocks-periodic", clients: d.Clients})
	fix.Register(&ec2EBSEncryptionFix{clients: d.Clients})
	fix.Register(&ec2TransitGatewayAutoAttachFix{clients: d.Clients})
	fix.Register(&guardDutyFix{clients: d.Clients})
	fix.Register(&securityHubFix{clients: d.Clients})
	fix.Register(newOpenSearchEncryptionAtRestFix(d.Clients))
	fix.Register(newOpenSearchNodeToNodeEncryptionFix(d.Clients))
	fix.Register(newOpenSearchHTTPSFix(d.Clients))
	fix.Register(&opensearchAuditLoggingFix{clients: d.Clients})

	// NO_IMPACT / MEDIUM (continued)
	fix.Register(&elastiCacheAutoFailoverFix{clients: d.Clients})
	fix.Register(&elastiCacheBackupFix{clients: d.Clients})
	fix.Register(&elastiCacheRedisBackupFix{clients: d.Clients})
	fix.Register(&redshiftEnhancedVPCRoutingFix{clients: d.Clients})
	fix.Register(&redshiftBackupFix{clients: d.Clients})
	fix.Register(newRedshiftAuditLoggingFix(d.Clients, p))
	fix.Register(&redshiftServerlessLogsFix{clients: d.Clients})
	fix.Register(&redshiftServerlessEnhancedVPCFix{clients: d.Clients})
	fix.Register(&macieFix{clients: d.Clients})
	fix.Register(&neptuneBackupRetentionFix{clients: d.Clients})
	fix.Register(&neptuneCloudWatchLogsFix{clients: d.Clients})
	fix.Register(&mqGeneralLoggingFix{clients: d.Clients})
	fix.Register(&mqAuditLoggingFix{checkID: "mq-cloudwatch-audit-logging-enabled", clients: d.Clients})
	fix.Register(&mqAuditLoggingFix{checkID: "mq-cloudwatch-audit-log-enabled", clients: d.Clients})
	fix.Register(&apigwV1ExecutionLoggingFix{clients: d.Clients})
	fix.Register(&albDropInvalidHeaderFix{clients: d.Clients})
	fix.Register(&elbDeletionProtectionFix{clients: d.Clients})
	fix.Register(&s3SSLOnlyFix{clients: d.Clients})
	fix.Register(&mariadbCloudWatchLogsFix{clients: d.Clients})
	fix.Register(&auroraMySQLBacktrackingFix{clients: d.Clients})
	fix.Register(&subnetAutoAssignPublicIPFix{clients: d.Clients})
	fix.Register(&dmsEndpointSSLFix{clients: d.Clients})
	fix.Register(&dmsReplicationTaskLoggingFix{checkID: "dms-replication-task-sourcedb-logging", source: true, clients: d.Clients})
	fix.Register(&dmsReplicationTaskLoggingFix{checkID: "dms-replication-task-targetdb-logging", source: false, clients: d.Clients})
	fix.Register(&apigwV1SSLFix{clients: d.Clients})
	fix.Register(&firehoseEncryptionFix{clients: d.Clients})
	fix.Register(&cloudTrailS3DataEventsFix{clients: d.Clients})
	fix.Register(&ssmAutomationLoggingFix{clients: d.Clients})
	fix.Register(&connectInstanceLoggingFix{clients: d.Clients})
	fix.Register(&route53QueryLoggingFix{clients: d.Clients})
	fix.Register(&cloudTrailS3AllDataEventsFix{checkID: "cloudtrail-all-read-s3-data-event-check", readWrite: cloudtrailtypes.ReadWriteTypeReadOnly, clients: d.Clients})
	fix.Register(&cloudTrailS3AllDataEventsFix{checkID: "cloudtrail-all-write-s3-data-event-check", readWrite: cloudtrailtypes.ReadWriteTypeWriteOnly, clients: d.Clients})
	fix.Register(&rdsPostgreSQLLoggingFix{clients: d.Clients})
	fix.Register(&rdsSQLServerLoggingFix{clients: d.Clients})
	fix.Register(&rdsProxyTLSFix{clients: d.Clients})
	fix.Register(&ecrImageScanningFix{clients: d.Clients})
	fix.Register(&ecrTagImmutabilityFix{clients: d.Clients})
	fix.Register(&ecrLifecyclePolicyFix{clients: d.Clients})
	fix.Register(&ec2ENISourceDestCheckFix{clients: d.Clients})
	fix.Register(&ec2LaunchTemplateIMDSv2Fix{clients: d.Clients})
	fix.Register(&ec2LaunchTemplatePublicIPFix{clients: d.Clients})
	fix.Register(&ec2ClientVPNLoggingFix{clients: d.Clients})
	fix.Register(&ec2VPNConnectionLoggingFix{clients: d.Clients})
	fix.Register(&sfnLoggingFix{clients: d.Clients})
	fix.Register(&fsxWindowsAuditLogFix{clients: d.Clients})
	fix.Register(&dataSyncTaskLoggingFix{clients: d.Clients})
	fix.Register(&dataSyncObjectStorageHTTPSFix{clients: d.Clients})
	fix.Register(&cwAlarmActionEnabledFix{clients: d.Clients})

	// NO_IMPACT / LOW (continued)
	fix.Register(&fsxOpenZFSCopyTagsFix{clients: d.Clients})
	fix.Register(&dataSyncTaskVerificationFix{clients: d.Clients})

	// NO_IMPACT / LOW (continued)
	fix.Register(&codeDeployAutoRollbackFix{clients: d.Clients})
	fix.Register(&codeDeployOutdatedInstancesFix{clients: d.Clients})
	fix.Register(&apigwV2MetricsFix{clients: d.Clients})
	fix.Register(&ebManagedUpdatesFix{clients: d.Clients})
	fix.Register(&ebEnhancedHealthFix{clients: d.Clients})
	fix.Register(&mskEnhancedMonitoringFix{clients: d.Clients})
	fix.Register(&ec2HopLimitFix{clients: d.Clients})
	fix.Register(&autoscalingCapacityRebalancingFix{clients: d.Clients})
	fix.Register(&autoscalingELBHealthCheckFix{clients: d.Clients})
	fix.Register(&apigwV1XRayFix{clients: d.Clients})
	fix.Register(&appsyncXRayFix{clients: d.Clients})

	// NO_IMPACT / MEDIUM (continued again)
	fix.Register(&sagemakerNotebookRootAccessFix{clients: d.Clients})
	fix.Register(&apigwV1AccessLogsFix{clients: d.Clients})
	fix.Register(&apigwV2AccessLogsFix{clients: d.Clients})
	fix.Register(&cloudFrontHTTPSFix{clients: d.Clients})
	fix.Register(&globalEndpointReplicationFix{clients: d.Clients})
	fix.Register(&rumCWLoggingFix{clients: d.Clients})
	fix.Register(&kinesisVideoRetentionFix{clients: d.Clients})
	fix.Register(&appRunnerObservabilityFix{clients: d.Clients})
	fix.Register(&s3KMSEncryptionFix{clients: d.Clients})
	fix.Register(&albDesyncModeFix{clients: d.Clients})
	fix.Register(&clbDesyncModeFix{clients: d.Clients})
	fix.Register(&codeBuildReportGroupEncryptionFix{clients: d.Clients})
	fix.Register(&cloudTrailS3PublicAccessFix{clients: d.Clients})

	// NO_IMPACT / HIGH (continued)
	fix.Register(&ebsSnapshotPublicFix{clients: d.Clients})
	fix.Register(&ec2LaunchTemplateEBSEncryptionFix{clients: d.Clients})
	fix.Register(&docDBSnapshotPublicFix{clients: d.Clients})
	fix.Register(&docDBTLSFix{clients: d.Clients})
	fix.Register(&dynamoDBKMSEncryptionFix{clients: d.Clients})
	fix.Register(&ecsFargatePlatformVersionFix{clients: d.Clients})
	fix.Register(&neptuneSnapshotPublicFix{clients: d.Clients})
	fix.Register(&rdsSnapshotPublicFix{clients: d.Clients})
	fix.Register(&snsKMSEncryptionFix{clients: d.Clients})
	fix.Register(&ssmDocumentNotPublicFix{clients: d.Clients})

	// DEGRADATION / MEDIUM (continued)
	fix.Register(&transferNoFTPFix{clients: d.Clients})

	// DEGRADATION / LOW
	fix.Register(&albHTTPSRedirectFix{clients: d.Clients})

	// DEGRADATION / HIGH
	fix.Register(&sqsNoPublicAccessFix{clients: d.Clients})
	fix.Register(&sqsNoFullAccessFix{clients: d.Clients})
	fix.Register(&snsNoPublicAccessFix{clients: d.Clients})
	fix.Register(&rdsInstancePublicAccessFix{clients: d.Clients})
	fix.Register(&mskPublicAccessFix{clients: d.Clients})
	fix.Register(&redshiftPublicAccessFix{clients: d.Clients})
	fix.Register(&redshiftServerlessPublicAccessFix{clients: d.Clients})

	// DEGRADATION / MEDIUM (instance-level, won't run without explicit --impact-filter)
	fix.Register(&ec2IMDSv2Fix{clients: d.Clients})

	// DEGRADATION / MEDIUM
	fix.Register(&s3ACLProhibitedFix{clients: d.Clients})
	fix.Register(newALBWAFFix(d.Clients))
	fix.Register(&eksEndpointNoPublicAccessFix{clients: d.Clients})

	// DOWN / HIGH
	fix.Register(&rdsMultiAZFix{clients: d.Clients})
}
